### ISSUE TITLE
Meaningful error message on bad input

### ISSUE THREAD

**Issue by tomasbedrich** [bezirovoviku/docx#3]
When I passed a markdown file to generator it gave me this error: `ZipArchive::getFromName(): Invalid or uninitialized Zip object`.
It would be nice to have more meaningful error message. Then we will be able to show the message to user as a reason why generating failed.

**Comment by SkaceKamen** [comment]
The machanism was in place, but I missed that ziparchive::open returns error code rather than plain false.
